---
kind: pipeline
type: docker
name: check

steps:
  - name: typechecks
    image: python
    commands:
    - pip install -r requirements.txt
    - python -m mypy telemood_app/__main__.py
    when:
      branch:
      - dev
      - main

---
kind: pipeline
type: docker
name: build

steps:
  - name: build-teleimage
    image: plugins/docker
    settings:
      repo: moodyknurd/telemood
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - main

