---
kind: pipeline
type: docker
name: typechecks

steps:
  - name: mypy-check
    image: python
    commands:
    - pip install -r requirements.txt
    - python -m mypy telemood_app/__main__.py
    when:
      branch:
      - dev

---
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-teleimage-amd64
  image: plugins/docker
  settings:
    repo: moodyknurd/telemood-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  force_tag: false
  #tags:
  #- amd64
  when:
    branch:
    - main

---
kind: pipeline
type: docker
name: build-arm32

platform:
  os: linux
  arch: arm

steps:
- name: build-teleimage-arm32
  image: plugins/docker
  settings:
    repo: moodyknurd/telemood-arm32
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  force_tag: false
  #tags:
  #- arm32
  when:
    branch:
    - main

