kind: pipeline
type: docker
name: everything

steps:
  - name: dev-check
    image: python
    commands:
    - pip install -r requirements.txt
    - python -m mypy telemood_app/__main__.py
    when:
      branch:
      - dev
  - name: main-check
    image: python
    commands:
    - pip install -r requirements.txt
    - python -m mypy telemood_app/__main__.py
    when:
      branch:
      - main
  - name: build-teleimage
    image: plugins/docker
    settings:
      repo: https://index.docker.io/v1/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
